#!/bin/bash

if [ $(pgrep -afc CryptoWorkbench) -gt 10 ]; then
    echo All slots used -- you\'ll have to wait.
    sleep 5
    exit;
fi

exec bash -c "time mono /opt/aninix/CryptoWorkbench/shell.exe --blind; read"
